// The "project context" section NestBox writes into CLAUDE.md, built only from what NestBox already knows.
// Env variables contribute key names only, never values. Only the text between the markers is ever replaced.
import { usesCrlf } from './docs';

export const CONTEXT_START = '<!-- nestbox:start -->';
export const CONTEXT_END = '<!-- nestbox:end -->';

export interface ContextFacts {
  packageManager: string | null;
  scripts: { name: string; command: string }[];
  runGroups: { name: string; scripts: string[] }[];
  workspaces: { name: string; relPath: string }[];
  prismaSchema: string | null;
  dockerCompose: string | null;
  /** PORT from the env tool (a number, the only env value NestBox ever uses). */
  port: number | null;
  /** Key names from .env.example. */
  envKeys: string[];
}

/** A Markdown code span that survives backticks inside, on one line. */
function code(text: string): string {
  const flat = text.replace(/\s*\r?\n\s*/g, ' ');
  const longest = Math.max(0, ...(flat.match(/`+/g) ?? []).map((run) => run.length));
  const fence = '`'.repeat(longest + 1);
  return longest > 0 ? `${fence} ${flat} ${fence}` : `${fence}${flat}${fence}`;
}

/** The whole section, markers included, with LF line endings. Deterministic for the same facts. */
export function buildBlock(facts: ContextFacts): string {
  const lines = [CONTEXT_START, '## Project context', '', '_Generated by NestBox. Edits between these markers are replaced on the next update._', ''];
  if (facts.packageManager) lines.push(`- Package manager: ${facts.packageManager}`);
  if (facts.port !== null) lines.push(`- Dev server port (PORT): ${facts.port}`);
  if (facts.prismaSchema) lines.push(`- Prisma schema: ${code(facts.prismaSchema)}`);
  if (facts.dockerCompose) lines.push(`- Docker Compose: ${code(facts.dockerCompose)}`);
  if (lines.at(-1) !== '') lines.push('');

  const section = (title: string, items: string[]) => {
    if (items.length === 0) return;
    lines.push(`### ${title}`, '', ...items, '');
  };
  section('Scripts', facts.scripts.map((s) => `- ${code(s.name)}: ${code(s.command)}`));
  section('Run groups', facts.runGroups.map((g) => `- ${g.name}: ${g.scripts.map(code).join(', ')}`));
  section('Workspace packages', facts.workspaces.map((w) => `- ${code(w.relPath)} (${w.name})`));
  if (facts.envKeys.length > 0) section('Environment variables', [`Keys from ${code('.env.example')}: ${facts.envKeys.map(code).join(', ')}`]);

  while (lines.at(-1) === '') lines.pop();
  lines.push(CONTEXT_END);
  return lines.join('\n');
}

/**
 * Puts block (LF) into existing: between the markers when both are there, else appended after one blank
 * line. The file's line endings are kept.
 */
export function applyBlock(existing: string, block: string): string {
  const eol = usesCrlf(existing) ? '\r\n' : '\n';
  const converted = block.split('\n').join(eol);
  const start = existing.indexOf(CONTEXT_START);
  const end = start === -1 ? -1 : existing.indexOf(CONTEXT_END, start);
  if (start !== -1 && end !== -1) return existing.slice(0, start) + converted + existing.slice(end + CONTEXT_END.length);
  const body = existing.replace(/(\r?\n|\s)*$/, '');
  return body === '' ? `${converted}${eol}` : `${body}${eol}${eol}${converted}${eol}`;
}
